# Generated by Django 5.1.15 on 2026-07-13 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=150)),
                ('material', models.CharField(choices=[('copper', 'Copper'), ('aluminum', 'Aluminum')], max_length=20)),
                ('conductor_size', models.CharField(help_text="e.g. '4/0 AWG', '500 kcmil', '95 mm²'", max_length=50)),
                ('insulation_type', models.CharField(help_text='e.g. XLPE, THWN-2', max_length=50)),
                ('ampacity_a', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ampacity (A)')),
                ('resistance_ohm_per_km', models.DecimalField(decimal_places=5, max_digits=9)),
                ('reactance_ohm_per_km', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('temp_rating_c', models.PositiveSmallIntegerField(help_text='Conductor temperature rating, °C')),
                ('voltage_rating_v', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Reserved for future cost estimation.', max_digits=8, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['manufacturer', 'conductor_size'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'manufacturer', 'conductor_size', 'material', 'insulation_type'), name='unique_cable_type_per_org')],
            },
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('pmax_w', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pmax (W)')),
                ('vmpp_v', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Vmpp (V)')),
                ('impp_a', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Impp (A)')),
                ('voc_v', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Voc (V)')),
                ('isc_a', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Isc (A)')),
                ('temp_coeff_voc_pct_per_c', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Temp. coefficient of Voc (%/°C)')),
                ('temp_coeff_isc_pct_per_c', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Temp. coefficient of Isc (%/°C)')),
                ('temp_coeff_pmax_pct_per_c', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Temp. coefficient of Pmax (%/°C)')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('depth_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_system_voltage_v', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Max. system voltage (V)')),
                ('series_fuse_rating_a', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Series fuse rating (A)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'manufacturer', 'model'), name='unique_module_type_per_org')],
            },
        ),
        migrations.CreateModel(
            name='PCSType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('power_rating_kva', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Power rating (kVA)')),
                ('nominal_ac_voltage_v', models.DecimalField(decimal_places=2, max_digits=7)),
                ('min_dc_voltage_v', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_dc_voltage_v', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mppt_min_voltage_v', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mppt_max_voltage_v', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_dc_current_a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_short_circuit_current_a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('num_mppt', models.PositiveSmallIntegerField(default=1)),
                ('efficiency_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Efficiency (%)')),
                ('has_integrated_transformer', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'manufacturer', 'model'), name='unique_pcs_type_per_org')],
            },
        ),
    ]
