# Generated by Django 5.1.15 on 2026-07-13 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCSInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text="e.g. 'INV-01', 'PCS-A1'", max_length=100)),
                ('pcs_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='equipment.pcstype')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='DCCircuit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text="e.g. 'MPPT-1'", max_length=100)),
                ('mppt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pcs_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_circuits', to='electrical.pcsinstance')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('voltage_kv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('utility_name', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='projects.project')),
            ],
            options={
                'verbose_name': 'POI',
                'verbose_name_plural': 'POIs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pcsinstance',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs_instances', to='electrical.site'),
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text="e.g. 'STR-1'", max_length=100)),
                ('modules_per_string', models.PositiveIntegerField()),
                ('combiner_identifier', models.CharField(blank=True, help_text='Optional label for the combiner box this string is wired through, if any.', max_length=100)),
                ('dc_circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='electrical.dccircuit')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strings', to='equipment.moduletype')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substations', to='electrical.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MVCircuit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text="e.g. 'MV-CKT-1'", max_length=100)),
                ('voltage_kv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pcs_instances', models.ManyToManyField(blank=True, related_name='mv_circuits', to='electrical.pcsinstance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mv_circuits', to='electrical.site')),
                ('substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mv_circuits', to='electrical.substation')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.AddConstraint(
            model_name='dccircuit',
            constraint=models.UniqueConstraint(fields=('pcs_instance', 'identifier'), name='unique_dc_circuit_identifier_per_pcs'),
        ),
        migrations.AddConstraint(
            model_name='poi',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_poi_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_site_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='pcsinstance',
            constraint=models.UniqueConstraint(fields=('site', 'identifier'), name='unique_pcs_identifier_per_site'),
        ),
        migrations.AddConstraint(
            model_name='string',
            constraint=models.UniqueConstraint(fields=('dc_circuit', 'identifier'), name='unique_string_identifier_per_dc_circuit'),
        ),
        migrations.AddConstraint(
            model_name='substation',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_substation_name_per_site'),
        ),
        migrations.AddConstraint(
            model_name='mvcircuit',
            constraint=models.UniqueConstraint(fields=('site', 'identifier'), name='unique_mv_circuit_identifier_per_site'),
        ),
    ]
